---
- name: install - add google apt key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: install - add google chrome apt repository
  apt_repository:
    update_cache: true
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: 'google-chrome'

- name: install - chrome packages
  apt:
    name: "{{ boxes_googlechrome_package_name }}"
    state: present
  loop_control:
    loop_var: boxes_googlechrome_package_name
  loop:
    - google-chrome-stable
